### ISSUE TITLE
[Umbrella] YouTube administration

### ISSUE THREAD

**Issue by justaugustus** [inclusivenaming/org#28]
- [x] Create brand account
- [x] Transfer existing channel to brand account: https://www.youtube.com/channel/UCP1oEIxHSl77RCWRPwRjdiQ
- [x] Update brand account logo
- [x] Add @celestehorgan, @justaugustus, and admin@... as brand account owners
- [ ] Transfer brand account primary ownership to admin@... (on or after 3/9) 
- [ ] Create workstream playlists
- [ ] Grant workstream leads access to individual playlists
- [ ] Grant @xmulligan Manager access to brand account
- [ ] Upload instructions for workstream leads
- [ ] Update YouTube information on website: https://github.com/inclusivenaming/website/issues/28
- [ ] Backfill any missing meetings

**Comment by justaugustus** [comment]
Transferred brand account primary ownership to admin@... and sent Manager access invite to @xmulligan.
