### ISSUE TITLE
[Umbrella issue] Projects for intake/evaluation

### ISSUE THREAD

**Issue by celestehorgan** [inclusivenaming/org#61]
Evaluate and house the following:

- [ ] DCILint configuration – ref: https://github.com/inclusivenaming/website/pull/38
- [ ] Alex.js
- [ ] Retext.js – ref:  https://github.com/inclusivenaming/org/issues/57
- [ ] TakeTwo https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo 
- [ ] https://github.com/ddavisjones/IBMInclusiveITLanguage

**Comment by mallory** [comment]
Another project to look at from the IETF implementing the NIST guidelines on inclusive terminology that is part of "Technical Series Publications Author Instructions" https://github.com/NTAP/isb-ietf-config
